/* ✅ COLUNAS OBRIGATÓRIAS */
SELECT
    TRY_TO_NUMBER(LTRIM(F.INSTALACAO, '0')) AS INSTALACAO,

    F.MES_COMPETENCIA AS MES,

    CASE
        WHEN I.ITEM_DOCUMENTO = 'ZRDENP' THEN 'DEMANDA_NP'
        WHEN I.ITEM_DOCUMENTO = 'ZRDEFP' THEN 'DEMANDA_FP'
        WHEN I.ITEM_DOCUMENTO = 'ZRDERV' THEN 'DEMANDA_RESERVA'
    END AS TIPO_DEMANDA,

    CAST(ROUND(I.CONSUMO, 2) AS NUMBER(18,2)) AS DEMANDA

/* ✅ TABELA PRINCIPAL DE CONSULTA */
FROM EQTLINFO_PRD.EQTL_RS.FATURAMENTO F

INNER JOIN EQTLINFO_PRD.EQTL_RS.ITENS_FATURAMENTO I
    ON I.DOCUMENTO_IMPRESSAO = F.DOCUMENTO_IMPRESSAO
   AND I.MES_COMPETENCIA = F.MES_COMPETENCIA

/* ✅ CONDIÇÕES DE CONSULTA */
WHERE
    F.MOTIVO_CRIACAO_IMPRESSAO = '01'
    AND F.TIPO_CALCULO = 'CP'

    AND I.ITEM_DOCUMENTO IN ('ZRDEFP','ZRDENP','ZRDERV')

    AND EXISTS (
        SELECT 1
        FROM EQTLINFO_PRD.EQTL_RS.TAB_EQUIPAMENTOS_MEDICAO X
        WHERE TRY_TO_NUMBER(LTRIM(X.INSTALACAO, '0')) =
              TRY_TO_NUMBER(LTRIM(F.INSTALACAO, '0'))
          AND X.DENOM_EQUIPAMENTO LIKE '%REMOTA%'
    )

/* ✅ ORDEM DA CONSULTA */
ORDER BY
    INSTALACAO ASC,
    MES DESC
