/* ✅ COLUNAS OBRIGATÓRIAS */
SELECT
    TRY_TO_NUMBER(LTRIM(INSTALACAO, '0')) AS INSTALACAO,

    CAST(DATA_INICIO AS DATE) AS DATA_INICIO,
    CAST(DATA_FIM AS DATE) AS DATA_FIM,

    CASE
        WHEN TIPO_DEMANDA IN ('DEMANDA_PONTA', 'DEMANDA_PONTA_LIVRE')
            THEN 'DEMANDA_PONTA'

        WHEN TIPO_DEMANDA IN ('DEMANDA_FORA_PONTA', 'DEMANDA_FORA_PONTA_LIVRE')
            THEN 'DEMANDA_FORA_PONTA'

        WHEN TIPO_DEMANDA IN ('DEMANDA_UNICA_LIVRE', 'DEMANDA_CONVENCIONAL')
            THEN 'DEMANDA_UNICA'

        ELSE NULL
    END AS TIPO_DEMANDA,

    CAST(ROUND(DEMANDA_CONTRATADA, 2) AS NUMBER(18,2)) AS DEMANDA_CONTRATADA

/* ✅ TABELA PRINCIPAL DE CONSULTA */
FROM EQTLINFO_PRD.EQTL_RS.TAB_DEMANDA_CONTRATADA

/* ✅ CONDIÇÕES DE CONSULTA */
WHERE TIPO_DEMANDA IN (
    'DEMANDA_PONTA',
    'DEMANDA_FORA_PONTA',
    'DEMANDA_PONTA_LIVRE',
    'DEMANDA_FORA_PONTA_LIVRE',
    'DEMANDA_UNICA_LIVRE',
    'DEMANDA_CONVENCIONAL'
)

/* ✅ ORDEM DA CONSULTA */
ORDER BY
    INSTALACAO,
    DATA_INICIO DESC;