/* ✅ COLUNAS OBRIGATÓRIAS */
SELECT 
    TRY_TO_NUMBER(LTRIM(A.INSTALACAO, '0')) AS INSTALACAO,

    A.STATUS_COMERCIAL AS STATUS,
    A.NOME AS CLIENTE,

    CASE
        WHEN A.CPF IS NOT NULL THEN
            REGEXP_REPLACE(
                REGEXP_REPLACE(
                    REGEXP_REPLACE(A.CPF, '([0-9]{3})([0-9]{3})([0-9]{3})([0-9]{2})', '\\1.\\2.\\3-\\4'),
                '[^0-9.-]', ''),
            '\\.\\.', '.')
        WHEN A.CNPJ IS NOT NULL THEN
            REGEXP_REPLACE(
                REGEXP_REPLACE(
                    REGEXP_REPLACE(A.CNPJ, '([0-9]{2})([0-9]{3})([0-9]{3})([0-9]{4})([0-9]{2})', '\\1.\\2.\\3/\\4-\\5'),
                '[^0-9./-]', ''),
            '\\.\\.', '.')
        ELSE NULL
    END AS DOCUMENTO,

    A.MOVE_IN::DATE AS INICIO_CONTRATO,
    A.MOVE_OUT::DATE AS FIM_CONTRATO,
    UPPER(A.SUBCLASSE) AS CLASSE,

    CASE
        WHEN A.MEDIDOR IS NOT NULL
             AND LEFT(A.MEDIDOR, 2) BETWEEN 'AA' AND 'ZZ'
        THEN SUBSTR(A.MEDIDOR, 3)
        ELSE A.MEDIDOR
    END AS MEDIDOR,

    A.FASE,

    M.FORNECEDOR,
    M.ANO_FABRICACAO AS ANO,

    CASE
        WHEN A.MICRO_GERADOR IS NULL THEN 'NAO'
        ELSE 'SIM'
    END AS MMGD,

    CASE
        WHEN NULLIF(TRIM(A.COMPLEMENTO), '') IS NULL
        THEN A.ENDERECO || ' ' || A.NUMERO
        ELSE A.ENDERECO || ' ' || A.NUMERO || ' ' || A.COMPLEMENTO
    END AS ENDERECO,

    REGEXP_REPLACE(TRIM(A.BAIRRO), '^[0-9]+\\s*', '') AS BAIRRO,

    A.MUNICIPIO,
    A.REGIONAL,

    P.DATA_FISCALIZACAO,
    P.CODIGO_IRREGULARIDADE AS IRREG


/* ✅ TABELA PRINCIPAL DE CONSULTA */
FROM EQTLINFO_PRD.EQTL_RS.TAB_CADASTRO A

/* ✅ PEGAR APENAS O MEDIDOR */
LEFT JOIN (
    SELECT
        NUMERO_SERIE,
        FORNECEDOR,
        ANO_FABRICACAO,
        ROW_NUMBER() OVER (
            PARTITION BY NUMERO_SERIE
            ORDER BY ANO_FABRICACAO DESC
        ) AS RN
    FROM EQTLINFO_PRD.EQTL_RS.TAB_EQUIPAMENTOS_MEDICAO
    WHERE UPPER(EQUIPAMENTO) LIKE '%MEDIDOR%'
) M
    ON A.MEDIDOR = M.NUMERO_SERIE
   AND M.RN = 1

/* ✅ ÚLTIMA FISCALIZAÇÃO */
LEFT JOIN (
    SELECT
        TRY_TO_NUMBER(LTRIM(INSTALACAO, '0')) AS INSTALACAO,
        TO_DATE(TO_VARCHAR(DATA_BAIXA), 'YYYYMMDD') AS DATA_FISCALIZACAO,
        TRY_TO_NUMBER(LTRIM(CODIGO_IRREGULARIDADE, '0')) AS CODIGO_IRREGULARIDADE,
        ROW_NUMBER() OVER (
            PARTITION BY TRY_TO_NUMBER(LTRIM(INSTALACAO, '0'))
            ORDER BY DATA_BAIXA DESC
        ) AS RN
    FROM EQTLINFO_PRD.EQTL_RS.ACOES_PERDAS
) P
    ON TRY_TO_NUMBER(LTRIM(A.INSTALACAO, '0')) = P.INSTALACAO
   AND P.RN = 1

/* 🔥 FILTRO CORRETO DE GRUPO A */
WHERE EXISTS (
    SELECT 1
    FROM EQTLINFO_PRD.EQTL_RS.TAB_EQUIPAMENTOS_MEDICAO X
    WHERE TRY_TO_NUMBER(LTRIM(X.INSTALACAO, '0')) =
          TRY_TO_NUMBER(LTRIM(A.INSTALACAO, '0'))
      AND X.DENOM_EQUIPAMENTO LIKE '%REMOTA%'
)

/* ✅ ORDEM DA CONSULTA */
ORDER BY A.MUNICIPIO