/* ✅ COLUNAS OBRIGATÓRIAS */
SELECT
    TRY_TO_NUMBER(LTRIM(A.INSTALACAO, '0')) AS INSTALACAO,

    A.MES_COMPETENCIA AS MES,
    
    CASE
        WHEN A.TIPO_REGISTRADOR = 'L4' THEN 'CONSUMO_ATIVO_NP'
        WHEN A.TIPO_REGISTRADOR = 'L8' THEN 'CONSUMO_ATIVO_FP'
        ELSE 'OUTROS'
    END AS TIPO_REGISTRO,
    
    CAST(ROUND(A.CONSUMO_REGISTRADO, 2) AS NUMBER(18,2)) AS CONSUMO,

    A.NOTA_LEITURA

/* ✅ TABELA PRINCIPAL DE CONSULTA */
FROM 
    EQTLINFO_PRD.EQTL_RS.LEITURA_CCS A

/* ✅ CONDIÇÕES DE CONSULTA */
WHERE
    A.MES_COMPETENCIA >= TO_CHAR(DATEADD(month, -12, CURRENT_DATE), 'YYYYMM')

    AND A.TIPO_REGISTRADOR IN ('L4', 'L8')

    AND EXISTS (
        SELECT 1
        FROM EQTLINFO_PRD.EQTL_RS.TAB_EQUIPAMENTOS_MEDICAO X
        WHERE TRY_TO_NUMBER(LTRIM(X.INSTALACAO, '0')) =
              TRY_TO_NUMBER(LTRIM(A.INSTALACAO, '0'))
          AND X.DENOM_CLASSE = 'REMOTA'
    )

/* ✅ ORDEM DA CONSULTA */
ORDER BY
    INSTALACAO ASC,
    MES DESC
