SELECT
    TRY_TO_NUMBER(LTRIM(A.INSTALACAO, '0')) AS INSTALACAO,
    A.LATITUDE,
    A.LONGITUDE
FROM 
    EQTLINFO_PRD.EQTL_RS.COORDENADAS_CCS A
WHERE
    EXISTS (
        SELECT 1
        FROM EQTLINFO_PRD.EQTL_RS.TAB_EQUIPAMENTOS_MEDICAO X
        WHERE TRY_TO_NUMBER(LTRIM(X.INSTALACAO, '0')) =
              TRY_TO_NUMBER(LTRIM(A.INSTALACAO, '0'))
          AND X.DENOM_EQUIPAMENTO LIKE '%REMOTA%'
    )
