/* ✅ COLUNAS OBRIGATÓRIAS */
SELECT 
    TRY_TO_NUMBER(LTRIM(A.INSTALACAO, '0')) AS INSTALACAO,
    
    CASE
        WHEN A.NUMERO_SERIE IS NOT NULL
             AND LEFT(A.NUMERO_SERIE, 2) BETWEEN 'AA' AND 'ZZ'
        THEN SUBSTR(A.NUMERO_SERIE, 3)
        ELSE A.NUMERO_SERIE
    END AS NUM_EQUIPAMENTO,
    
    CASE
        WHEN A.EQUIPAMENTO IS NULL AND A.DENOM_EQUIPAMENTO LIKE '%REMOTA%'
            THEN 'REMOTA'
        WHEN A.EQUIPAMENTO IS NULL AND A.DENOM_EQUIPAMENTO LIKE '%CHAV%'
            THEN 'CHAVE'
        ELSE A.EQUIPAMENTO
    END AS EQUIPAMENTO,
    
    A.FORNECEDOR AS FABRICANTE,
    A.ANO_FABRICACAO AS ANO,
    UPPER(A.DENOM_EQUIPAMENTO) AS CLASSIFICACAO,
    A.GRUP_ENROLAMENTO,

    CASE
        WHEN A.RTC IS NULL
            THEN A.RTP
        ELSE A.RTC
    END AS RTC_RTP,
    
    A.CLASSE_ISOLACAO,
    A.PRIM_CORRENTE,
    A.SEC_CORRENTE,
    A.PRIM_TENSAO,
    A.SEC_TENSAO

/* ✅ TABELA PRINCIPAL DE CONSULTA */    
FROM 
    EQTLINFO_PRD.EQTL_RS.TAB_EQUIPAMENTOS_MEDICAO A

/* ✅ CONDIÇÕES DE CONSULTA */
WHERE 
    A.DENOM_CLASSE IN (
        'CHAVE DE AFERIÇÃO',
        'REMOTA',
        'TRANSFORMADOR DE CORRENTE',
        'TRANSFORMADOR DE POTENCIAL'
    )

    AND EXISTS (
        SELECT 1
        FROM EQTLINFO_PRD.EQTL_RS.TAB_EQUIPAMENTOS_MEDICAO X
        WHERE TRY_TO_NUMBER(LTRIM(X.INSTALACAO, '0'))
              = TRY_TO_NUMBER(LTRIM(A.INSTALACAO, '0'))
            AND X.DENOM_CLASSE = 'REMOTA'
    )